### ISSUE TITLE
path for libclang.dylib

### ISSUE THREAD

**Issue by michaelsbradleyjr** [alexmurray/cstyle#1]
On my mac (10.11.5), I needed to do the following to get `cstyle` to work:

`cd /usr/local/lib && ln -s /Library/Developer/CommandLineTools/usr/lib/libclang.dylib libclang.dylib`

Is there a better/proper way?

**Comment by alexmurray** [comment]
Thanks for the bug report - can you try the 'fix-issue-1' branch and see if this resolves it (without needing the symlink?) I don't have OS X so I can't test it but I think it might do the trick...

**Comment by michaelsbradleyjr** [comment]
It tried the `fix-issue-1` branch, and it's working for me, with the symlink I put in place having been removed.

**Comment by alexmurray** [comment]
Awesome, thanks for the confirmation.
